In [4]:
#1 Import required libraries

import pandas as pd
import numpy as np

In [5]:
#2 Load dataset

df = pd.read_excel("C:/Users/rd000/Desktop/Analyst/113_Ecommerce/Raw Data & Ques/Ecommerce_Unclean_Project 1.xlsx")

In [6]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,ORD1012,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025
511,ORD1013,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025
512,ORD1014,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
513,ORD1015,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
514,ORD1016,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025

In [7]:
#3 Explore the dataset

# View top 5 records
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [8]:
# View dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       515 non-null    object
 1   Order_Date     515 non-null    object
 2   Customer_Name  515 non-null    object
 3   Email          515 non-null    object
 4   Phone          493 non-null    float64
 5   City           515 non-null    object
 6   State          515 non-null    object
 7   Product        515 non-null    object
 8   Category       515 non-null    object
 9   Qty            450 non-null    float64
 10  Unit_Price     465 non-null    float64
 11  Discount       448 non-null    object
 12  Payment_Mode   515 non-null    object
 13  Order_Status   515 non-null    object
 14  Delivery_Date  495 non-null    object
dtypes: float64(3), object(12)
memory usage: 60.5+ KB

In [9]:
# Get statistical summary

df.describe()

              Phone         Qty   Unit_Price
count  4.930000e+02  450.000000   465.000000
mean   9.542689e+09    2.804444  3161.150538
std    2.634413e+08    1.964491  2968.046005
min    9.104441e+09   -1.000000   499.000000
25%    9.313737e+09    1.000000   999.000000
50%    9.533399e+09    3.000000  1999.000000
75%    9.789375e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [10]:
# View dataset shape

df.shape

(515, 15)

In [11]:
#4 Check missing values

df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              65
Unit_Price       50
Discount         67
Payment_Mode      0
Order_Status      0
Delivery_Date    20
dtype: int64

In [12]:
#5 Check & remove duplicate records

df.duplicated().sum()

np.int64(11)

In [13]:
# Remove duplicate records

df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
#6 Replace invalid values (Replace N/A, NULL, " " with NaN

df=df.replace(['N/A','NULL',' '],np.nan)

C:\Users\rd000\AppData\Local\Temp\ipykernel_29584\142207598.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace(['N/A','NULL',' '],np.nan)

In [16]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15.0,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,ORD1501,28-04-2025,Amit,amit26@gmail.com,9.873317e+09,Lucknow,UP,Chair,Furniture,-1.0,1499.0,15.0,Wallet,Delivered,04-05-2025
511,ORD1013,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025
512,ORD1014,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
513,ORD1015,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
514,ORD1016,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025

In [17]:
#7 Remove extra spaces

df = df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

In [18]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15.0,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,ORD1501,28-04-2025,Amit,amit26@gmail.com,9.873317e+09,Lucknow,UP,Chair,Furniture,-1.0,1499.0,15.0,Wallet,Delivered,04-05-2025
511,ORD1013,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025
512,ORD1014,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
513,ORD1015,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
514,ORD1016,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025

In [19]:
#8 Standardize text format (Proper case)

df["Customer_Name"]=df["Customer_Name"].str.title()

df["City"]=df["City"].str.title()

df["State"]=df["State"].str.title()

In [20]:
#9 Validate Email addresses

df = df[df['Email'].str.contains('@',na=False)].copy()

In [21]:
#10 Convert date columns

df['Order_Date'] = pd.to_datetime(df['Order_Date'], format = 'mixed', dayfirst= True, errors='coerce')
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'], format = 'mixed', dayfirst= True, errors='coerce')

In [22]:
#11 Convert columns into numeric-columns

cols = ['Qty','Unit_Price','Discount']

for c in cols:
    df[c]= pd.to_numeric(df[c],errors= 'coerce')

In [23]:
#12 Remove invalid quantity

df= df[df['Qty']>0]

In [24]:
#13 Fill missing values

df['Discount'] = df['Discount'].fillna(0)

df['Phone'] = df['Phone'].fillna('Unknown')

df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [25]:
#14 Feature engineering

# Create new columns

df['Sales']= df['Qty'] * df['Unit_Price']
df['Net_Amount']= df['Sales'] - (df['Sales'] * df['Discount']/100)
df['Profit']= df['Net_Amount'] * 0.2
df['Month']= df['Order_Date'].dt.month_name()
df['Year']= df['Order_Date'].dt.year
df['Weekday']= df['Order_Date'].dt.day_name()

In [26]:
df['Order_Date'].dt.strftime('%d-%m-%Y')
df['Delivery_Date'].dt.strftime('%d-%m-%Y')

0      03-07-2025
1      09-02-2025
2      08-05-2025
5      18-02-2025
6      27-02-2025
          ...
498    15-05-2025
511    09-03-2025
512    16-01-2025
513    16-01-2025
514    16-01-2025
Name: Delivery_Date, Length: 374, dtype: object

In [27]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-07-03,7996.0,7996.00,1599.20,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2025-02-09,24995.0,19996.00,3999.20,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,2025-05-08,5997.0,5697.15,1139.43,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2025-02-18,1497.0,1197.60,239.52,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,ORD1500,2025-05-15,Priya,priya67@gmail.com,9848200695.0,Pune,Maharashtra,Laptop,Electronics,3.0,...,15.0,UPI,Delivered,2025-05-15,NaN,NaN,NaN,May,2025.0,Thursday
511,ORD1013,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,2025-03-09,2997.0,2847.15,569.43,March,2025.0,Monday
512,ORD1014,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0,Saturday
513,ORD1015,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0,Saturday
514,ORD1016,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0,Saturday

In [28]:
#15 Final data-checking

# View dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 374 entries, 0 to 514
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       368 non-null    object
 1   Order_Date     362 non-null    datetime64[ns]
 2   Customer_Name  374 non-null    object
 3   Email          374 non-null    object
 4   Phone          374 non-null    object
 5   City           374 non-null    object
 6   State          374 non-null    object
 7   Product        374 non-null    object
 8   Category       374 non-null    object
 9   Qty            374 non-null    float64
 10  Unit_Price     339 non-null    float64
 11  Discount       374 non-null    float64
 12  Payment_Mode   374 non-null    object
 13  Order_Status   374 non-null    object
 14  Delivery_Date  372 non-null    datetime64[ns]
 15  Sales          339 non-null    float64
 16  Net_Amount     339 non-null    float64
 17  Profit         339 non-null    float64
 18  Month          362 non-null    object
 19  Year           362 non-null    float64
 20  Weekday        362 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 64.3+ KB

In [29]:
# Check missing values

df.isnull().sum()

Order_ID          6
Order_Date       12
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       35
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Sales            35
Net_Amount       35
Profit           35
Month            12
Year             12
Weekday          12
dtype: int64

In [30]:
# Get statistical summary

df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,362,374.000000,339.000000,374.000000,372,339.000000,339.000000,339.000000,362.0
mean,2025-04-04 00:03:58.674033408,3.331551,3234.693215,7.767380,2025-04-09 22:50:19.354838784,11006.112094,10157.951032,2031.590206,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-01-05 00:00:00,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.000000,2025-02-22 18:00:00,2599.000000,2398.400000,479.680000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,5.000000,2025-04-12 00:00:00,5997.000000,5996.000000,1199.200000,2025.0
75%,2025-05-18 12:00:00,5.000000,4999.000000,15.000000,2025-05-25 00:00:00,12995.000000,12871.225000,2574.245000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-07-08 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.459817,3018.413957,7.862894,NaN,12133.914990,11440.640347,2288.128069,0.0

In [31]:
#16 Export clean data

df.to_csv('Clean_Ecommerce.csv',index= False)

In [32]:
#17 Import data into ssms

from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://RDsDevice\SQLEXPRESS01/Project 1"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

In [33]:
# Export dataframe to ssms

df.to_sql(
    name="E_Orders",
    con=engine,
    if_exists="replace",
    index=False
)

C:\Users\rd000\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

77

In [34]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-07-03,7996.0,7996.00,1599.20,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2025-02-09,24995.0,19996.00,3999.20,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,2025-05-08,5997.0,5697.15,1139.43,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2025-02-18,1497.0,1197.60,239.52,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,ORD1500,2025-05-15,Priya,priya67@gmail.com,9848200695.0,Pune,Maharashtra,Laptop,Electronics,3.0,...,15.0,UPI,Delivered,2025-05-15,NaN,NaN,NaN,May,2025.0,Thursday
511,ORD1013,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,2025-03-09,2997.0,2847.15,569.43,March,2025.0,Monday
512,ORD1014,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0,Saturday
513,ORD1015,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0,Saturday
514,ORD1016,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0,Saturday